real,user,sys
9.368,9.230,0.090
9.097,9.000,0.060
8.705,8.530,0.140
8.920,8.730,0.150
9.202,9.040,0.130
8.929,8.750,0.150
9.357,9.170,0.150
9.026,8.810,0.180
9.287,9.080,0.170
8.923,8.750,0.140
9.946,9.750,0.160
10.272,10.070,0.170
10.180,10.040,0.100
10.314,10.120,0.150
10.051,9.860,0.150
10.366,10.170,0.160
10.202,10.010,0.150
10.035,9.750,0.240
9.994,9.770,0.190
9.947,9.760,0.150
9.970,9.800,0.140
9.926,9.780,0.110
9.952,9.760,0.160
10.005,9.870,0.090
9.869,9.770,0.060
9.940,9.720,0.180
9.827,9.670,0.120
9.898,9.750,0.110
9.880,9.740,0.110
9.863,9.650,0.160
10.063,9.940,0.100
9.978,9.820,0.130
9.988,9.830,0.130
10.020,9.830,0.150
9.976,9.860,0.100
9.980,9.830,0.120
9.984,9.790,0.160
10.048,9.900,0.120
10.015,9.850,0.140
9.934,9.780,0.130
./demo2.sh: 21: ./demo2.sh: time: not found
./demo2.sh: 21: ./demo2.sh: time: not found
./demo2.sh: 21: ./demo2.sh: time: not found
./demo2.sh: 21: ./demo2.sh: time: not found
./demo2.sh: 21: ./demo2.sh: time: not found
./demo2.sh: 21: ./demo2.sh: time: not found
./demo2.sh: 21: ./demo2.sh: time: not found
./demo2.sh: 21: ./demo2.sh: time: not found
./demo2.sh: 21: ./demo2.sh: time: not found
./demo2.sh: 21: ./demo2.sh: time: not found
/usr/bin/env: th: No such file or directory
Traceback (most recent call last):
  File "../demos/compare.py", line 101, in <module>
    d = getRep(img1) - getRep(img2)
  File "../demos/compare.py", line 92, in getRep
    rep = net.forward(alignedFace)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 156, in forward
    rep = self.forwardPath(t)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 113, in forwardPath
    """.format(self.cmd, self.p.stdout.read()))
Exception: 


OpenFace: `openface_server.lua` subprocess has died.

+ Is the Torch command `th` on your PATH? Check with `which th`.

+ If `th` is on your PATH, try running `./util/profile-network.lua`
  to see if Torch can correctly load and run the network.

  + If this gives illegal instruction errors, see the section on
    this in our FAQ at http://cmusatyalab.github.io/openface/faq/

  + In Docker, use a Bash login shell or source
     /root/torch/install/bin/torch-activate for the Torch environment.

+ See this GitHub issue if you are running on a non-64-bit machine:
  https://github.com/cmusatyalab/openface/issues/42

+ Please post further issues to our mailing list at
  https://groups.google.com/forum/#!forum/cmu-openface

Diagnostic information:

cmd: ['/usr/bin/env', 'th', '/usr/local/lib/python2.7/dist-packages/openface/openface_server.lua', '-model', '/root/openface/demos/../models/openface/nn4.small2.v1.t7', '-imgDim', '96']

============

stdout: 

2.107,2.010,0.090
/usr/bin/env: th: No such file or directory
Traceback (most recent call last):
  File "../demos/compare.py", line 101, in <module>
    d = getRep(img1) - getRep(img2)
  File "../demos/compare.py", line 92, in getRep
    rep = net.forward(alignedFace)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 156, in forward
    rep = self.forwardPath(t)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 113, in forwardPath
    """.format(self.cmd, self.p.stdout.read()))
Exception: 


OpenFace: `openface_server.lua` subprocess has died.

+ Is the Torch command `th` on your PATH? Check with `which th`.

+ If `th` is on your PATH, try running `./util/profile-network.lua`
  to see if Torch can correctly load and run the network.

  + If this gives illegal instruction errors, see the section on
    this in our FAQ at http://cmusatyalab.github.io/openface/faq/

  + In Docker, use a Bash login shell or source
     /root/torch/install/bin/torch-activate for the Torch environment.

+ See this GitHub issue if you are running on a non-64-bit machine:
  https://github.com/cmusatyalab/openface/issues/42

+ Please post further issues to our mailing list at
  https://groups.google.com/forum/#!forum/cmu-openface

Diagnostic information:

cmd: ['/usr/bin/env', 'th', '/usr/local/lib/python2.7/dist-packages/openface/openface_server.lua', '-model', '/root/openface/demos/../models/openface/nn4.small2.v1.t7', '-imgDim', '96']

============

stdout: 

2.149,2.020,0.120
/usr/bin/env: th: No such file or directory
Traceback (most recent call last):
  File "../demos/compare.py", line 101, in <module>
    d = getRep(img1) - getRep(img2)
  File "../demos/compare.py", line 92, in getRep
    rep = net.forward(alignedFace)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 156, in forward
    rep = self.forwardPath(t)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 113, in forwardPath
    """.format(self.cmd, self.p.stdout.read()))
Exception: 


OpenFace: `openface_server.lua` subprocess has died.

+ Is the Torch command `th` on your PATH? Check with `which th`.

+ If `th` is on your PATH, try running `./util/profile-network.lua`
  to see if Torch can correctly load and run the network.

  + If this gives illegal instruction errors, see the section on
    this in our FAQ at http://cmusatyalab.github.io/openface/faq/

  + In Docker, use a Bash login shell or source
     /root/torch/install/bin/torch-activate for the Torch environment.

+ See this GitHub issue if you are running on a non-64-bit machine:
  https://github.com/cmusatyalab/openface/issues/42

+ Please post further issues to our mailing list at
  https://groups.google.com/forum/#!forum/cmu-openface

Diagnostic information:

cmd: ['/usr/bin/env', 'th', '/usr/local/lib/python2.7/dist-packages/openface/openface_server.lua', '-model', '/root/openface/demos/../models/openface/nn4.small2.v1.t7', '-imgDim', '96']

============

stdout: 

2.112,2.040,0.060
/usr/bin/env: th: No such file or directory
Traceback (most recent call last):
  File "../demos/compare.py", line 101, in <module>
    d = getRep(img1) - getRep(img2)
  File "../demos/compare.py", line 92, in getRep
    rep = net.forward(alignedFace)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 156, in forward
    rep = self.forwardPath(t)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 113, in forwardPath
    """.format(self.cmd, self.p.stdout.read()))
Exception: 


OpenFace: `openface_server.lua` subprocess has died.

+ Is the Torch command `th` on your PATH? Check with `which th`.

+ If `th` is on your PATH, try running `./util/profile-network.lua`
  to see if Torch can correctly load and run the network.

  + If this gives illegal instruction errors, see the section on
    this in our FAQ at http://cmusatyalab.github.io/openface/faq/

  + In Docker, use a Bash login shell or source
     /root/torch/install/bin/torch-activate for the Torch environment.

+ See this GitHub issue if you are running on a non-64-bit machine:
  https://github.com/cmusatyalab/openface/issues/42

+ Please post further issues to our mailing list at
  https://groups.google.com/forum/#!forum/cmu-openface

Diagnostic information:

cmd: ['/usr/bin/env', 'th', '/usr/local/lib/python2.7/dist-packages/openface/openface_server.lua', '-model', '/root/openface/demos/../models/openface/nn4.small2.v1.t7', '-imgDim', '96']

============

stdout: 

2.080,1.950,0.120
/usr/bin/env: th: No such file or directory
Traceback (most recent call last):
  File "../demos/compare.py", line 101, in <module>
    d = getRep(img1) - getRep(img2)
  File "../demos/compare.py", line 92, in getRep
    rep = net.forward(alignedFace)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 156, in forward
    rep = self.forwardPath(t)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 113, in forwardPath
    """.format(self.cmd, self.p.stdout.read()))
Exception: 


OpenFace: `openface_server.lua` subprocess has died.

+ Is the Torch command `th` on your PATH? Check with `which th`.

+ If `th` is on your PATH, try running `./util/profile-network.lua`
  to see if Torch can correctly load and run the network.

  + If this gives illegal instruction errors, see the section on
    this in our FAQ at http://cmusatyalab.github.io/openface/faq/

  + In Docker, use a Bash login shell or source
     /root/torch/install/bin/torch-activate for the Torch environment.

+ See this GitHub issue if you are running on a non-64-bit machine:
  https://github.com/cmusatyalab/openface/issues/42

+ Please post further issues to our mailing list at
  https://groups.google.com/forum/#!forum/cmu-openface

Diagnostic information:

cmd: ['/usr/bin/env', 'th', '/usr/local/lib/python2.7/dist-packages/openface/openface_server.lua', '-model', '/root/openface/demos/../models/openface/nn4.small2.v1.t7', '-imgDim', '96']

============

stdout: 

2.135,2.070,0.060
/usr/bin/env: th: No such file or directory
Traceback (most recent call last):
  File "../demos/compare.py", line 101, in <module>
    d = getRep(img1) - getRep(img2)
  File "../demos/compare.py", line 92, in getRep
    rep = net.forward(alignedFace)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 156, in forward
    rep = self.forwardPath(t)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 113, in forwardPath
    """.format(self.cmd, self.p.stdout.read()))
Exception: 


OpenFace: `openface_server.lua` subprocess has died.

+ Is the Torch command `th` on your PATH? Check with `which th`.

+ If `th` is on your PATH, try running `./util/profile-network.lua`
  to see if Torch can correctly load and run the network.

  + If this gives illegal instruction errors, see the section on
    this in our FAQ at http://cmusatyalab.github.io/openface/faq/

  + In Docker, use a Bash login shell or source
     /root/torch/install/bin/torch-activate for the Torch environment.

+ See this GitHub issue if you are running on a non-64-bit machine:
  https://github.com/cmusatyalab/openface/issues/42

+ Please post further issues to our mailing list at
  https://groups.google.com/forum/#!forum/cmu-openface

Diagnostic information:

cmd: ['/usr/bin/env', 'th', '/usr/local/lib/python2.7/dist-packages/openface/openface_server.lua', '-model', '/root/openface/demos/../models/openface/nn4.small2.v1.t7', '-imgDim', '96']

============

stdout: 

2.170,2.080,0.080
/usr/bin/env: th: No such file or directory
Traceback (most recent call last):
  File "../demos/compare.py", line 101, in <module>
    d = getRep(img1) - getRep(img2)
  File "../demos/compare.py", line 92, in getRep
    rep = net.forward(alignedFace)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 156, in forward
    rep = self.forwardPath(t)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 113, in forwardPath
    """.format(self.cmd, self.p.stdout.read()))
Exception: 


OpenFace: `openface_server.lua` subprocess has died.

+ Is the Torch command `th` on your PATH? Check with `which th`.

+ If `th` is on your PATH, try running `./util/profile-network.lua`
  to see if Torch can correctly load and run the network.

  + If this gives illegal instruction errors, see the section on
    this in our FAQ at http://cmusatyalab.github.io/openface/faq/

  + In Docker, use a Bash login shell or source
     /root/torch/install/bin/torch-activate for the Torch environment.

+ See this GitHub issue if you are running on a non-64-bit machine:
  https://github.com/cmusatyalab/openface/issues/42

+ Please post further issues to our mailing list at
  https://groups.google.com/forum/#!forum/cmu-openface

Diagnostic information:

cmd: ['/usr/bin/env', 'th', '/usr/local/lib/python2.7/dist-packages/openface/openface_server.lua', '-model', '/root/openface/demos/../models/openface/nn4.small2.v1.t7', '-imgDim', '96']

============

stdout: 

2.099,1.980,0.110
/usr/bin/env: th: No such file or directory
Traceback (most recent call last):
  File "../demos/compare.py", line 101, in <module>
    d = getRep(img1) - getRep(img2)
  File "../demos/compare.py", line 92, in getRep
    rep = net.forward(alignedFace)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 156, in forward
    rep = self.forwardPath(t)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 113, in forwardPath
    """.format(self.cmd, self.p.stdout.read()))
Exception: 


OpenFace: `openface_server.lua` subprocess has died.

+ Is the Torch command `th` on your PATH? Check with `which th`.

+ If `th` is on your PATH, try running `./util/profile-network.lua`
  to see if Torch can correctly load and run the network.

  + If this gives illegal instruction errors, see the section on
    this in our FAQ at http://cmusatyalab.github.io/openface/faq/

  + In Docker, use a Bash login shell or source
     /root/torch/install/bin/torch-activate for the Torch environment.

+ See this GitHub issue if you are running on a non-64-bit machine:
  https://github.com/cmusatyalab/openface/issues/42

+ Please post further issues to our mailing list at
  https://groups.google.com/forum/#!forum/cmu-openface

Diagnostic information:

cmd: ['/usr/bin/env', 'th', '/usr/local/lib/python2.7/dist-packages/openface/openface_server.lua', '-model', '/root/openface/demos/../models/openface/nn4.small2.v1.t7', '-imgDim', '96']

============

stdout: 

2.157,2.080,0.070
/usr/bin/env: th: No such file or directory
Traceback (most recent call last):
  File "../demos/compare.py", line 101, in <module>
    d = getRep(img1) - getRep(img2)
  File "../demos/compare.py", line 92, in getRep
    rep = net.forward(alignedFace)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 156, in forward
    rep = self.forwardPath(t)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 113, in forwardPath
    """.format(self.cmd, self.p.stdout.read()))
Exception: 


OpenFace: `openface_server.lua` subprocess has died.

+ Is the Torch command `th` on your PATH? Check with `which th`.

+ If `th` is on your PATH, try running `./util/profile-network.lua`
  to see if Torch can correctly load and run the network.

  + If this gives illegal instruction errors, see the section on
    this in our FAQ at http://cmusatyalab.github.io/openface/faq/

  + In Docker, use a Bash login shell or source
     /root/torch/install/bin/torch-activate for the Torch environment.

+ See this GitHub issue if you are running on a non-64-bit machine:
  https://github.com/cmusatyalab/openface/issues/42

+ Please post further issues to our mailing list at
  https://groups.google.com/forum/#!forum/cmu-openface

Diagnostic information:

cmd: ['/usr/bin/env', 'th', '/usr/local/lib/python2.7/dist-packages/openface/openface_server.lua', '-model', '/root/openface/demos/../models/openface/nn4.small2.v1.t7', '-imgDim', '96']

============

stdout: 

2.284,2.200,0.070
/usr/bin/env: th: No such file or directory
Traceback (most recent call last):
  File "../demos/compare.py", line 101, in <module>
    d = getRep(img1) - getRep(img2)
  File "../demos/compare.py", line 92, in getRep
    rep = net.forward(alignedFace)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 156, in forward
    rep = self.forwardPath(t)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 113, in forwardPath
    """.format(self.cmd, self.p.stdout.read()))
Exception: 


OpenFace: `openface_server.lua` subprocess has died.

+ Is the Torch command `th` on your PATH? Check with `which th`.

+ If `th` is on your PATH, try running `./util/profile-network.lua`
  to see if Torch can correctly load and run the network.

  + If this gives illegal instruction errors, see the section on
    this in our FAQ at http://cmusatyalab.github.io/openface/faq/

  + In Docker, use a Bash login shell or source
     /root/torch/install/bin/torch-activate for the Torch environment.

+ See this GitHub issue if you are running on a non-64-bit machine:
  https://github.com/cmusatyalab/openface/issues/42

+ Please post further issues to our mailing list at
  https://groups.google.com/forum/#!forum/cmu-openface

Diagnostic information:

cmd: ['/usr/bin/env', 'th', '/usr/local/lib/python2.7/dist-packages/openface/openface_server.lua', '-model', '/root/openface/demos/../models/openface/nn4.small2.v1.t7', '-imgDim', '96']

============

stdout: 

2.237,2.140,0.090
/usr/bin/env: th: No such file or directory
Traceback (most recent call last):
  File "../demos/compare.py", line 101, in <module>
    d = getRep(img1) - getRep(img2)
  File "../demos/compare.py", line 92, in getRep
    rep = net.forward(alignedFace)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 156, in forward
    rep = self.forwardPath(t)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 113, in forwardPath
    """.format(self.cmd, self.p.stdout.read()))
Exception: 


OpenFace: `openface_server.lua` subprocess has died.

+ Is the Torch command `th` on your PATH? Check with `which th`.

+ If `th` is on your PATH, try running `./util/profile-network.lua`
  to see if Torch can correctly load and run the network.

  + If this gives illegal instruction errors, see the section on
    this in our FAQ at http://cmusatyalab.github.io/openface/faq/

  + In Docker, use a Bash login shell or source
     /root/torch/install/bin/torch-activate for the Torch environment.

+ See this GitHub issue if you are running on a non-64-bit machine:
  https://github.com/cmusatyalab/openface/issues/42

+ Please post further issues to our mailing list at
  https://groups.google.com/forum/#!forum/cmu-openface

Diagnostic information:

cmd: ['/usr/bin/env', 'th', '/usr/local/lib/python2.7/dist-packages/openface/openface_server.lua', '-model', '/root/openface/demos/../models/openface/nn4.small2.v1.t7', '-imgDim', '96']

============

stdout: 

2.365,2.250,0.100
/usr/bin/env: th: No such file or directory
Traceback (most recent call last):
  File "../demos/compare.py", line 101, in <module>
    d = getRep(img1) - getRep(img2)
  File "../demos/compare.py", line 92, in getRep
    rep = net.forward(alignedFace)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 156, in forward
    rep = self.forwardPath(t)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 113, in forwardPath
    """.format(self.cmd, self.p.stdout.read()))
Exception: 


OpenFace: `openface_server.lua` subprocess has died.

+ Is the Torch command `th` on your PATH? Check with `which th`.

+ If `th` is on your PATH, try running `./util/profile-network.lua`
  to see if Torch can correctly load and run the network.

  + If this gives illegal instruction errors, see the section on
    this in our FAQ at http://cmusatyalab.github.io/openface/faq/

  + In Docker, use a Bash login shell or source
     /root/torch/install/bin/torch-activate for the Torch environment.

+ See this GitHub issue if you are running on a non-64-bit machine:
  https://github.com/cmusatyalab/openface/issues/42

+ Please post further issues to our mailing list at
  https://groups.google.com/forum/#!forum/cmu-openface

Diagnostic information:

cmd: ['/usr/bin/env', 'th', '/usr/local/lib/python2.7/dist-packages/openface/openface_server.lua', '-model', '/root/openface/demos/../models/openface/nn4.small2.v1.t7', '-imgDim', '96']

============

stdout: 

2.313,2.220,0.080
/usr/bin/env: th: No such file or directory
Traceback (most recent call last):
  File "../demos/compare.py", line 101, in <module>
    d = getRep(img1) - getRep(img2)
  File "../demos/compare.py", line 92, in getRep
    rep = net.forward(alignedFace)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 156, in forward
    rep = self.forwardPath(t)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 113, in forwardPath
    """.format(self.cmd, self.p.stdout.read()))
Exception: 


OpenFace: `openface_server.lua` subprocess has died.

+ Is the Torch command `th` on your PATH? Check with `which th`.

+ If `th` is on your PATH, try running `./util/profile-network.lua`
  to see if Torch can correctly load and run the network.

  + If this gives illegal instruction errors, see the section on
    this in our FAQ at http://cmusatyalab.github.io/openface/faq/

  + In Docker, use a Bash login shell or source
     /root/torch/install/bin/torch-activate for the Torch environment.

+ See this GitHub issue if you are running on a non-64-bit machine:
  https://github.com/cmusatyalab/openface/issues/42

+ Please post further issues to our mailing list at
  https://groups.google.com/forum/#!forum/cmu-openface

Diagnostic information:

cmd: ['/usr/bin/env', 'th', '/usr/local/lib/python2.7/dist-packages/openface/openface_server.lua', '-model', '/root/openface/demos/../models/openface/nn4.small2.v1.t7', '-imgDim', '96']

============

stdout: 

2.356,2.260,0.080
/usr/bin/env: th: No such file or directory
Traceback (most recent call last):
  File "../demos/compare.py", line 101, in <module>
    d = getRep(img1) - getRep(img2)
  File "../demos/compare.py", line 92, in getRep
    rep = net.forward(alignedFace)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 156, in forward
    rep = self.forwardPath(t)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 113, in forwardPath
    """.format(self.cmd, self.p.stdout.read()))
Exception: 


OpenFace: `openface_server.lua` subprocess has died.

+ Is the Torch command `th` on your PATH? Check with `which th`.

+ If `th` is on your PATH, try running `./util/profile-network.lua`
  to see if Torch can correctly load and run the network.

  + If this gives illegal instruction errors, see the section on
    this in our FAQ at http://cmusatyalab.github.io/openface/faq/

  + In Docker, use a Bash login shell or source
     /root/torch/install/bin/torch-activate for the Torch environment.

+ See this GitHub issue if you are running on a non-64-bit machine:
  https://github.com/cmusatyalab/openface/issues/42

+ Please post further issues to our mailing list at
  https://groups.google.com/forum/#!forum/cmu-openface

Diagnostic information:

cmd: ['/usr/bin/env', 'th', '/usr/local/lib/python2.7/dist-packages/openface/openface_server.lua', '-model', '/root/openface/demos/../models/openface/nn4.small2.v1.t7', '-imgDim', '96']

============

stdout: 

2.365,2.250,0.100
/usr/bin/env: th: No such file or directory
Traceback (most recent call last):
  File "../demos/compare.py", line 101, in <module>
    d = getRep(img1) - getRep(img2)
  File "../demos/compare.py", line 92, in getRep
    rep = net.forward(alignedFace)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 156, in forward
    rep = self.forwardPath(t)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 113, in forwardPath
    """.format(self.cmd, self.p.stdout.read()))
Exception: 


OpenFace: `openface_server.lua` subprocess has died.

+ Is the Torch command `th` on your PATH? Check with `which th`.

+ If `th` is on your PATH, try running `./util/profile-network.lua`
  to see if Torch can correctly load and run the network.

  + If this gives illegal instruction errors, see the section on
    this in our FAQ at http://cmusatyalab.github.io/openface/faq/

  + In Docker, use a Bash login shell or source
     /root/torch/install/bin/torch-activate for the Torch environment.

+ See this GitHub issue if you are running on a non-64-bit machine:
  https://github.com/cmusatyalab/openface/issues/42

+ Please post further issues to our mailing list at
  https://groups.google.com/forum/#!forum/cmu-openface

Diagnostic information:

cmd: ['/usr/bin/env', 'th', '/usr/local/lib/python2.7/dist-packages/openface/openface_server.lua', '-model', '/root/openface/demos/../models/openface/nn4.small2.v1.t7', '-imgDim', '96']

============

stdout: 

2.342,2.220,0.110
/usr/bin/env: th: No such file or directory
Traceback (most recent call last):
  File "../demos/compare.py", line 101, in <module>
    d = getRep(img1) - getRep(img2)
  File "../demos/compare.py", line 92, in getRep
    rep = net.forward(alignedFace)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 156, in forward
    rep = self.forwardPath(t)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 113, in forwardPath
    """.format(self.cmd, self.p.stdout.read()))
Exception: 


OpenFace: `openface_server.lua` subprocess has died.

+ Is the Torch command `th` on your PATH? Check with `which th`.

+ If `th` is on your PATH, try running `./util/profile-network.lua`
  to see if Torch can correctly load and run the network.

  + If this gives illegal instruction errors, see the section on
    this in our FAQ at http://cmusatyalab.github.io/openface/faq/

  + In Docker, use a Bash login shell or source
     /root/torch/install/bin/torch-activate for the Torch environment.

+ See this GitHub issue if you are running on a non-64-bit machine:
  https://github.com/cmusatyalab/openface/issues/42

+ Please post further issues to our mailing list at
  https://groups.google.com/forum/#!forum/cmu-openface

Diagnostic information:

cmd: ['/usr/bin/env', 'th', '/usr/local/lib/python2.7/dist-packages/openface/openface_server.lua', '-model', '/root/openface/demos/../models/openface/nn4.small2.v1.t7', '-imgDim', '96']

============

stdout: 

2.350,2.220,0.120
/usr/bin/env: th: No such file or directory
Traceback (most recent call last):
  File "../demos/compare.py", line 101, in <module>
    d = getRep(img1) - getRep(img2)
  File "../demos/compare.py", line 92, in getRep
    rep = net.forward(alignedFace)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 156, in forward
    rep = self.forwardPath(t)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 113, in forwardPath
    """.format(self.cmd, self.p.stdout.read()))
Exception: 


OpenFace: `openface_server.lua` subprocess has died.

+ Is the Torch command `th` on your PATH? Check with `which th`.

+ If `th` is on your PATH, try running `./util/profile-network.lua`
  to see if Torch can correctly load and run the network.

  + If this gives illegal instruction errors, see the section on
    this in our FAQ at http://cmusatyalab.github.io/openface/faq/

  + In Docker, use a Bash login shell or source
     /root/torch/install/bin/torch-activate for the Torch environment.

+ See this GitHub issue if you are running on a non-64-bit machine:
  https://github.com/cmusatyalab/openface/issues/42

+ Please post further issues to our mailing list at
  https://groups.google.com/forum/#!forum/cmu-openface

Diagnostic information:

cmd: ['/usr/bin/env', 'th', '/usr/local/lib/python2.7/dist-packages/openface/openface_server.lua', '-model', '/root/openface/demos/../models/openface/nn4.small2.v1.t7', '-imgDim', '96']

============

stdout: 

2.339,2.250,0.080
/usr/bin/env: th: No such file or directory
Traceback (most recent call last):
  File "../demos/compare.py", line 101, in <module>
    d = getRep(img1) - getRep(img2)
  File "../demos/compare.py", line 92, in getRep
    rep = net.forward(alignedFace)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 156, in forward
    rep = self.forwardPath(t)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 113, in forwardPath
    """.format(self.cmd, self.p.stdout.read()))
Exception: 


OpenFace: `openface_server.lua` subprocess has died.

+ Is the Torch command `th` on your PATH? Check with `which th`.

+ If `th` is on your PATH, try running `./util/profile-network.lua`
  to see if Torch can correctly load and run the network.

  + If this gives illegal instruction errors, see the section on
    this in our FAQ at http://cmusatyalab.github.io/openface/faq/

  + In Docker, use a Bash login shell or source
     /root/torch/install/bin/torch-activate for the Torch environment.

+ See this GitHub issue if you are running on a non-64-bit machine:
  https://github.com/cmusatyalab/openface/issues/42

+ Please post further issues to our mailing list at
  https://groups.google.com/forum/#!forum/cmu-openface

Diagnostic information:

cmd: ['/usr/bin/env', 'th', '/usr/local/lib/python2.7/dist-packages/openface/openface_server.lua', '-model', '/root/openface/demos/../models/openface/nn4.small2.v1.t7', '-imgDim', '96']

============

stdout: 

2.333,2.260,0.060
/usr/bin/env: th: No such file or directory
Traceback (most recent call last):
  File "../demos/compare.py", line 101, in <module>
    d = getRep(img1) - getRep(img2)
  File "../demos/compare.py", line 92, in getRep
    rep = net.forward(alignedFace)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 156, in forward
    rep = self.forwardPath(t)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 113, in forwardPath
    """.format(self.cmd, self.p.stdout.read()))
Exception: 


OpenFace: `openface_server.lua` subprocess has died.

+ Is the Torch command `th` on your PATH? Check with `which th`.

+ If `th` is on your PATH, try running `./util/profile-network.lua`
  to see if Torch can correctly load and run the network.

  + If this gives illegal instruction errors, see the section on
    this in our FAQ at http://cmusatyalab.github.io/openface/faq/

  + In Docker, use a Bash login shell or source
     /root/torch/install/bin/torch-activate for the Torch environment.

+ See this GitHub issue if you are running on a non-64-bit machine:
  https://github.com/cmusatyalab/openface/issues/42

+ Please post further issues to our mailing list at
  https://groups.google.com/forum/#!forum/cmu-openface

Diagnostic information:

cmd: ['/usr/bin/env', 'th', '/usr/local/lib/python2.7/dist-packages/openface/openface_server.lua', '-model', '/root/openface/demos/../models/openface/nn4.small2.v1.t7', '-imgDim', '96']

============

stdout: 

2.378,2.240,0.130
/usr/bin/env: th: No such file or directory
Traceback (most recent call last):
  File "../demos/compare.py", line 101, in <module>
    d = getRep(img1) - getRep(img2)
  File "../demos/compare.py", line 92, in getRep
    rep = net.forward(alignedFace)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 156, in forward
    rep = self.forwardPath(t)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 113, in forwardPath
    """.format(self.cmd, self.p.stdout.read()))
Exception: 


OpenFace: `openface_server.lua` subprocess has died.

+ Is the Torch command `th` on your PATH? Check with `which th`.

+ If `th` is on your PATH, try running `./util/profile-network.lua`
  to see if Torch can correctly load and run the network.

  + If this gives illegal instruction errors, see the section on
    this in our FAQ at http://cmusatyalab.github.io/openface/faq/

  + In Docker, use a Bash login shell or source
     /root/torch/install/bin/torch-activate for the Torch environment.

+ See this GitHub issue if you are running on a non-64-bit machine:
  https://github.com/cmusatyalab/openface/issues/42

+ Please post further issues to our mailing list at
  https://groups.google.com/forum/#!forum/cmu-openface

Diagnostic information:

cmd: ['/usr/bin/env', 'th', '/usr/local/lib/python2.7/dist-packages/openface/openface_server.lua', '-model', '/root/openface/demos/../models/openface/nn4.small2.v1.t7', '-imgDim', '96']

============

stdout: 

2.375,2.270,0.090
/usr/bin/env: th: No such file or directory
Traceback (most recent call last):
  File "../demos/compare.py", line 101, in <module>
    d = getRep(img1) - getRep(img2)
  File "../demos/compare.py", line 92, in getRep
    rep = net.forward(alignedFace)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 156, in forward
    rep = self.forwardPath(t)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 113, in forwardPath
    """.format(self.cmd, self.p.stdout.read()))
Exception: 


OpenFace: `openface_server.lua` subprocess has died.

+ Is the Torch command `th` on your PATH? Check with `which th`.

+ If `th` is on your PATH, try running `./util/profile-network.lua`
  to see if Torch can correctly load and run the network.

  + If this gives illegal instruction errors, see the section on
    this in our FAQ at http://cmusatyalab.github.io/openface/faq/

  + In Docker, use a Bash login shell or source
     /root/torch/install/bin/torch-activate for the Torch environment.

+ See this GitHub issue if you are running on a non-64-bit machine:
  https://github.com/cmusatyalab/openface/issues/42

+ Please post further issues to our mailing list at
  https://groups.google.com/forum/#!forum/cmu-openface

Diagnostic information:

cmd: ['/usr/bin/env', 'th', '/usr/local/lib/python2.7/dist-packages/openface/openface_server.lua', '-model', '/root/openface/demos/../models/openface/nn4.small2.v1.t7', '-imgDim', '96']

============

stdout: 

2.372,2.270,0.090
/usr/bin/env: th: No such file or directory
Traceback (most recent call last):
  File "../demos/compare.py", line 101, in <module>
    d = getRep(img1) - getRep(img2)
  File "../demos/compare.py", line 92, in getRep
    rep = net.forward(alignedFace)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 156, in forward
    rep = self.forwardPath(t)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 113, in forwardPath
    """.format(self.cmd, self.p.stdout.read()))
Exception: 


OpenFace: `openface_server.lua` subprocess has died.

+ Is the Torch command `th` on your PATH? Check with `which th`.

+ If `th` is on your PATH, try running `./util/profile-network.lua`
  to see if Torch can correctly load and run the network.

  + If this gives illegal instruction errors, see the section on
    this in our FAQ at http://cmusatyalab.github.io/openface/faq/

  + In Docker, use a Bash login shell or source
     /root/torch/install/bin/torch-activate for the Torch environment.

+ See this GitHub issue if you are running on a non-64-bit machine:
  https://github.com/cmusatyalab/openface/issues/42

+ Please post further issues to our mailing list at
  https://groups.google.com/forum/#!forum/cmu-openface

Diagnostic information:

cmd: ['/usr/bin/env', 'th', '/usr/local/lib/python2.7/dist-packages/openface/openface_server.lua', '-model', '/root/openface/demos/../models/openface/nn4.small2.v1.t7', '-imgDim', '96']

============

stdout: 

2.390,2.300,0.080
/usr/bin/env: th: No such file or directory
Traceback (most recent call last):
  File "../demos/compare.py", line 101, in <module>
    d = getRep(img1) - getRep(img2)
  File "../demos/compare.py", line 92, in getRep
    rep = net.forward(alignedFace)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 156, in forward
    rep = self.forwardPath(t)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 113, in forwardPath
    """.format(self.cmd, self.p.stdout.read()))
Exception: 


OpenFace: `openface_server.lua` subprocess has died.

+ Is the Torch command `th` on your PATH? Check with `which th`.

+ If `th` is on your PATH, try running `./util/profile-network.lua`
  to see if Torch can correctly load and run the network.

  + If this gives illegal instruction errors, see the section on
    this in our FAQ at http://cmusatyalab.github.io/openface/faq/

  + In Docker, use a Bash login shell or source
     /root/torch/install/bin/torch-activate for the Torch environment.

+ See this GitHub issue if you are running on a non-64-bit machine:
  https://github.com/cmusatyalab/openface/issues/42

+ Please post further issues to our mailing list at
  https://groups.google.com/forum/#!forum/cmu-openface

Diagnostic information:

cmd: ['/usr/bin/env', 'th', '/usr/local/lib/python2.7/dist-packages/openface/openface_server.lua', '-model', '/root/openface/demos/../models/openface/nn4.small2.v1.t7', '-imgDim', '96']

============

stdout: 

2.343,2.270,0.060
/usr/bin/env: th: No such file or directory
Traceback (most recent call last):
  File "../demos/compare.py", line 101, in <module>
    d = getRep(img1) - getRep(img2)
  File "../demos/compare.py", line 92, in getRep
    rep = net.forward(alignedFace)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 156, in forward
    rep = self.forwardPath(t)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 113, in forwardPath
    """.format(self.cmd, self.p.stdout.read()))
Exception: 


OpenFace: `openface_server.lua` subprocess has died.

+ Is the Torch command `th` on your PATH? Check with `which th`.

+ If `th` is on your PATH, try running `./util/profile-network.lua`
  to see if Torch can correctly load and run the network.

  + If this gives illegal instruction errors, see the section on
    this in our FAQ at http://cmusatyalab.github.io/openface/faq/

  + In Docker, use a Bash login shell or source
     /root/torch/install/bin/torch-activate for the Torch environment.

+ See this GitHub issue if you are running on a non-64-bit machine:
  https://github.com/cmusatyalab/openface/issues/42

+ Please post further issues to our mailing list at
  https://groups.google.com/forum/#!forum/cmu-openface

Diagnostic information:

cmd: ['/usr/bin/env', 'th', '/usr/local/lib/python2.7/dist-packages/openface/openface_server.lua', '-model', '/root/openface/demos/../models/openface/nn4.small2.v1.t7', '-imgDim', '96']

============

stdout: 

2.343,2.260,0.070
/usr/bin/env: th: No such file or directory
Traceback (most recent call last):
  File "../demos/compare.py", line 101, in <module>
    d = getRep(img1) - getRep(img2)
  File "../demos/compare.py", line 92, in getRep
    rep = net.forward(alignedFace)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 156, in forward
    rep = self.forwardPath(t)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 113, in forwardPath
    """.format(self.cmd, self.p.stdout.read()))
Exception: 


OpenFace: `openface_server.lua` subprocess has died.

+ Is the Torch command `th` on your PATH? Check with `which th`.

+ If `th` is on your PATH, try running `./util/profile-network.lua`
  to see if Torch can correctly load and run the network.

  + If this gives illegal instruction errors, see the section on
    this in our FAQ at http://cmusatyalab.github.io/openface/faq/

  + In Docker, use a Bash login shell or source
     /root/torch/install/bin/torch-activate for the Torch environment.

+ See this GitHub issue if you are running on a non-64-bit machine:
  https://github.com/cmusatyalab/openface/issues/42

+ Please post further issues to our mailing list at
  https://groups.google.com/forum/#!forum/cmu-openface

Diagnostic information:

cmd: ['/usr/bin/env', 'th', '/usr/local/lib/python2.7/dist-packages/openface/openface_server.lua', '-model', '/root/openface/demos/../models/openface/nn4.small2.v1.t7', '-imgDim', '96']

============

stdout: 

2.325,2.240,0.070
/usr/bin/env: th: No such file or directory
Traceback (most recent call last):
  File "../demos/compare.py", line 101, in <module>
    d = getRep(img1) - getRep(img2)
  File "../demos/compare.py", line 92, in getRep
    rep = net.forward(alignedFace)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 156, in forward
    rep = self.forwardPath(t)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 113, in forwardPath
    """.format(self.cmd, self.p.stdout.read()))
Exception: 


OpenFace: `openface_server.lua` subprocess has died.

+ Is the Torch command `th` on your PATH? Check with `which th`.

+ If `th` is on your PATH, try running `./util/profile-network.lua`
  to see if Torch can correctly load and run the network.

  + If this gives illegal instruction errors, see the section on
    this in our FAQ at http://cmusatyalab.github.io/openface/faq/

  + In Docker, use a Bash login shell or source
     /root/torch/install/bin/torch-activate for the Torch environment.

+ See this GitHub issue if you are running on a non-64-bit machine:
  https://github.com/cmusatyalab/openface/issues/42

+ Please post further issues to our mailing list at
  https://groups.google.com/forum/#!forum/cmu-openface

Diagnostic information:

cmd: ['/usr/bin/env', 'th', '/usr/local/lib/python2.7/dist-packages/openface/openface_server.lua', '-model', '/root/openface/demos/../models/openface/nn4.small2.v1.t7', '-imgDim', '96']

============

stdout: 

2.343,2.240,0.090
/usr/bin/env: th: No such file or directory
Traceback (most recent call last):
  File "../demos/compare.py", line 101, in <module>
    d = getRep(img1) - getRep(img2)
  File "../demos/compare.py", line 92, in getRep
    rep = net.forward(alignedFace)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 156, in forward
    rep = self.forwardPath(t)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 113, in forwardPath
    """.format(self.cmd, self.p.stdout.read()))
Exception: 


OpenFace: `openface_server.lua` subprocess has died.

+ Is the Torch command `th` on your PATH? Check with `which th`.

+ If `th` is on your PATH, try running `./util/profile-network.lua`
  to see if Torch can correctly load and run the network.

  + If this gives illegal instruction errors, see the section on
    this in our FAQ at http://cmusatyalab.github.io/openface/faq/

  + In Docker, use a Bash login shell or source
     /root/torch/install/bin/torch-activate for the Torch environment.

+ See this GitHub issue if you are running on a non-64-bit machine:
  https://github.com/cmusatyalab/openface/issues/42

+ Please post further issues to our mailing list at
  https://groups.google.com/forum/#!forum/cmu-openface

Diagnostic information:

cmd: ['/usr/bin/env', 'th', '/usr/local/lib/python2.7/dist-packages/openface/openface_server.lua', '-model', '/root/openface/demos/../models/openface/nn4.small2.v1.t7', '-imgDim', '96']

============

stdout: 

2.354,2.270,0.070
/usr/bin/env: th: No such file or directory
Traceback (most recent call last):
  File "../demos/compare.py", line 101, in <module>
    d = getRep(img1) - getRep(img2)
  File "../demos/compare.py", line 92, in getRep
    rep = net.forward(alignedFace)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 156, in forward
    rep = self.forwardPath(t)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 113, in forwardPath
    """.format(self.cmd, self.p.stdout.read()))
Exception: 


OpenFace: `openface_server.lua` subprocess has died.

+ Is the Torch command `th` on your PATH? Check with `which th`.

+ If `th` is on your PATH, try running `./util/profile-network.lua`
  to see if Torch can correctly load and run the network.

  + If this gives illegal instruction errors, see the section on
    this in our FAQ at http://cmusatyalab.github.io/openface/faq/

  + In Docker, use a Bash login shell or source
     /root/torch/install/bin/torch-activate for the Torch environment.

+ See this GitHub issue if you are running on a non-64-bit machine:
  https://github.com/cmusatyalab/openface/issues/42

+ Please post further issues to our mailing list at
  https://groups.google.com/forum/#!forum/cmu-openface

Diagnostic information:

cmd: ['/usr/bin/env', 'th', '/usr/local/lib/python2.7/dist-packages/openface/openface_server.lua', '-model', '/root/openface/demos/../models/openface/nn4.small2.v1.t7', '-imgDim', '96']

============

stdout: 

2.345,2.300,0.030
/usr/bin/env: th: No such file or directory
Traceback (most recent call last):
  File "../demos/compare.py", line 101, in <module>
    d = getRep(img1) - getRep(img2)
  File "../demos/compare.py", line 92, in getRep
    rep = net.forward(alignedFace)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 156, in forward
    rep = self.forwardPath(t)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 113, in forwardPath
    """.format(self.cmd, self.p.stdout.read()))
Exception: 


OpenFace: `openface_server.lua` subprocess has died.

+ Is the Torch command `th` on your PATH? Check with `which th`.

+ If `th` is on your PATH, try running `./util/profile-network.lua`
  to see if Torch can correctly load and run the network.

  + If this gives illegal instruction errors, see the section on
    this in our FAQ at http://cmusatyalab.github.io/openface/faq/

  + In Docker, use a Bash login shell or source
     /root/torch/install/bin/torch-activate for the Torch environment.

+ See this GitHub issue if you are running on a non-64-bit machine:
  https://github.com/cmusatyalab/openface/issues/42

+ Please post further issues to our mailing list at
  https://groups.google.com/forum/#!forum/cmu-openface

Diagnostic information:

cmd: ['/usr/bin/env', 'th', '/usr/local/lib/python2.7/dist-packages/openface/openface_server.lua', '-model', '/root/openface/demos/../models/openface/nn4.small2.v1.t7', '-imgDim', '96']

============

stdout: 

2.370,2.340,0.020
/usr/bin/env: th: No such file or directory
Traceback (most recent call last):
  File "../demos/compare.py", line 101, in <module>
    d = getRep(img1) - getRep(img2)
  File "../demos/compare.py", line 92, in getRep
    rep = net.forward(alignedFace)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 156, in forward
    rep = self.forwardPath(t)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 113, in forwardPath
    """.format(self.cmd, self.p.stdout.read()))
Exception: 


OpenFace: `openface_server.lua` subprocess has died.

+ Is the Torch command `th` on your PATH? Check with `which th`.

+ If `th` is on your PATH, try running `./util/profile-network.lua`
  to see if Torch can correctly load and run the network.

  + If this gives illegal instruction errors, see the section on
    this in our FAQ at http://cmusatyalab.github.io/openface/faq/

  + In Docker, use a Bash login shell or source
     /root/torch/install/bin/torch-activate for the Torch environment.

+ See this GitHub issue if you are running on a non-64-bit machine:
  https://github.com/cmusatyalab/openface/issues/42

+ Please post further issues to our mailing list at
  https://groups.google.com/forum/#!forum/cmu-openface

Diagnostic information:

cmd: ['/usr/bin/env', 'th', '/usr/local/lib/python2.7/dist-packages/openface/openface_server.lua', '-model', '/root/openface/demos/../models/openface/nn4.small2.v1.t7', '-imgDim', '96']

============

stdout: 

2.372,2.230,0.130
